services:
  mariadb:
    image: mariadb
    container_name: mariadb6
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_USER_PASSWORD: ${MARIADB_USER_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - mariadb_datab6:/var/lib/mysql
      - ./Videojuegos.sql://docker-entrypoint-initdb.d/Videojuegos.sql:ro
    user: mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadminb6
    restart: unless-stopped
    environment:
      - PMA_HOST=mariadb
    ports:
      - 7106:80
    depends_on:
      - mariadb
  python:
    build: ./api
    container_name: pythonb6
    restart: unless-stopped
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      PORT: ${PORT}
      HOST: ${HOST}
      TOKEN_SECRET: ${TOKEN_SECRET}
      ALGORITMO: ${ALGORITMO}
    depends_on:
      - mariadb
  apache:
    build:
      context: .  # El contexto es la ra√≠z del proyecto
      dockerfile: apache/Dockerfile
    container_name: apacheb6
    restart: unless-stopped
    ports:
      - 6106:80
    depends_on:
      - python

volumes:
  mariadb_datab6:
