apiVersion: v1
kind: Service
metadata:
  name: mariadb6
<<<<<<< Updated upstream
  namespace: grupo6
=======
  namespace: grupob6
>>>>>>> Stashed changes
spec:
  ports:
    - port: 3306
  selector:
    app: mariadb6
